APP_NAME = "Pharmacy Management System"
APP_VERSION = "0.1.0"
APP_ORG = "PharmacyManagement"
DEFAULT_HTTP_TIMEOUT = 30
DEFAULT_SYNC_INTERVAL = 10
DEFAULT_PAGE_SIZE = 50
MAX_SYNC_BATCH_SIZE = 50
STANDARD_MAX_RETRIES = 10
AUDIT_MAX_RETRIES = 50

