# Generated by Django 5.1.15 on 2026-09-25 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('local_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=20)),
                ('sync_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'branch_id', 'created_at'], name='audit_audit_organiz_54652f_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx')],
            },
        ),
    ]
