# Generated by Django 5.1.15 on 2026-09-25 16:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_alter_device_options'),
        ('organizations', '0001_initial'),
        ('pricing', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('version', models.IntegerField()),
                ('local_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_status', models.CharField(default='SYNCED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='branches.branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='organizations.organization')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pricing.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_histories', to='products.product')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
    ]
