# Generated by Django 5.1.15 on 2026-09-25 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.CharField(default='professional', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('grace_period_days', models.IntegerField(default=14)),
                ('auto_renew', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_code', models.CharField(max_length=100)),
                ('feature_value', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='licensing.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'feature_code')},
            },
        ),
    ]
