# Generated by Django 5.1.15 on 2026-09-27 17:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pharmacy Subscription', 'verbose_name_plural': 'Pharmacy Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monnify_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monnify_account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monnify_account_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monnify_bank_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monnify_bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000.00'), help_text='Monthly subscription fee in NGN set manually for this pharmacy.', max_digits=12),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('250000.00'), help_text='Yearly subscription fee in NGN set manually for this pharmacy.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAST_DUE', 'PAST_DUE'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment_reference', models.CharField(max_length=120, unique=True)),
                ('monnify_transaction_reference', models.CharField(blank=True, default='', max_length=120)),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly (30 Days)'), ('YEARLY', 'Yearly (365 Days)')], default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('days_credited', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid / Confirmed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=500)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='licensing.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
