# Generated by Django 5.1.15 on 2026-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_subscription_options_subscription_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('PAST_DUE', 'PAST_DUE'), ('SUSPENDED', 'SUSPENDED'), ('CANCELLED', 'CANCELLED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=20),
        ),
    ]
