# Generated by Django 5.1.15 on 2026-09-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SyncDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('operation', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('target_scope', models.CharField(max_length=20)),
                ('source_device_id', models.UUIDField(null=True)),
                ('source_event_id', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('source_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.branch')),
                ('target_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='branches.branch')),
            ],
        ),
    ]
