# Generated by Django 5.1.15 on 2026-09-27 18:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_alter_device_options'),
        ('organizations', '0001_initial'),
        ('sync', '0002_alter_syncdelivery_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_code', models.CharField(db_index=True, max_length=50)),
                ('branch_name', models.CharField(default='Main Branch', max_length=255)),
                ('device_code', models.CharField(blank=True, default='POS01', max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('compressed_payload', models.BinaryField()),
                ('note', models.CharField(blank=True, default='Auto-Sync Cloud Backup', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloud_backups', to='branches.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_backups', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Branch Cloud Backup',
                'verbose_name_plural': 'Branch Cloud Backups (Max 4 / Branch)',
                'ordering': ['-created_at'],
            },
        ),
    ]
