# Generated by Django 5.1.15 on 2026-09-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-created_at']},
        ),
    ]
