import uuid
from datetime import date, datetime, timedelta, timezone
from decimal import Decimal
from desktop.app.config.app_config import AppConfig
from desktop.app.db.database import DatabaseManager
from desktop.app.db.models import (
    Organization,
    Branch,
    User,
    Category,
    Product,
    ProductBranch,
    Price,
    Batch,
    BranchInventory,
    InventoryMovement,
)
from shared.enums import MovementType, BatchStatus, InventoryStatus

ITEMS_DATA = [
    # 1. Analgesics, Antipyretics & Anti-inflammatory (Pain & Fever)
    {
        "name": "Paracetamol 500mg Tablets (Pack of 100)",
        "generic_name": "Paracetamol",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-PARA-500",
        "barcode": "615100000001",
        "prescription": False,
        "cost": Decimal("400.00"),
        "price": Decimal("650.00"),
        "qty": 350,
        "days_to_expiry": 730,
    },
    {
        "name": "Panadol Extra Tablets (Pack of 24)",
        "generic_name": "Paracetamol / Caffeine",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-PAN-EXT-24",
        "barcode": "615100000002",
        "prescription": False,
        "cost": Decimal("950.00"),
        "price": Decimal("1400.00"),
        "qty": 180,
        "days_to_expiry": 600,
    },
    {
        "name": "Ibuprofen 400mg Tablets (Pack of 100)",
        "generic_name": "Ibuprofen",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-IBU-400",
        "barcode": "615100000003",
        "prescription": False,
        "cost": Decimal("850.00"),
        "price": Decimal("1300.00"),
        "qty": 220,
        "days_to_expiry": 540,
    },
    {
        "name": "Diclofenac Potassium 50mg Tablets (Cataflam Generic)",
        "generic_name": "Diclofenac Potassium",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-DICLO-50",
        "barcode": "615100000004",
        "prescription": True,
        "cost": Decimal("650.00"),
        "price": Decimal("1100.00"),
        "qty": 140,
        "days_to_expiry": 450,
    },
    {
        "name": "Tramadol 50mg Capsules (Pack of 10)",
        "generic_name": "Tramadol Hydrochloride",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-TRAM-50",
        "barcode": "615100000005",
        "prescription": True,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 50,
        "days_to_expiry": 400,
    },
    {
        "name": "Naproxen 500mg Tablets (Pack of 20)",
        "generic_name": "Naproxen",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-NAP-500",
        "barcode": "615100000006",
        "prescription": True,
        "cost": Decimal("1500.00"),
        "price": Decimal("2400.00"),
        "qty": 75,
        "days_to_expiry": 700,
    },
    {
        "name": "Aspirin 75mg Low Dose Dispersible (Cardiprin Generic)",
        "generic_name": "Acetylsalicylic Acid",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-ASP-75",
        "barcode": "615100000007",
        "prescription": False,
        "cost": Decimal("700.00"),
        "price": Decimal("1200.00"),
        "qty": 200,
        "days_to_expiry": 800,
    },
    {
        "name": "Ketoprofen Gel 2.5% (30g Tube)",
        "generic_name": "Ketoprofen",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-KETO-GEL",
        "barcode": "615100000008",
        "prescription": False,
        "cost": Decimal("1100.00"),
        "price": Decimal("1800.00"),
        "qty": 90,
        "days_to_expiry": 650,
    },
    {
        "name": "Paracetamol Syrup 120mg/5ml (100ml Bottle)",
        "generic_name": "Paracetamol",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-PARA-SYR-100",
        "barcode": "615100000009",
        "prescription": False,
        "cost": Decimal("350.00"),
        "price": Decimal("600.00"),
        "qty": 130,
        "days_to_expiry": 380,
    },
    {
        "name": "Aceclofenac + Paracetamol (Hifenac-P)",
        "generic_name": "Aceclofenac / Paracetamol",
        "category": "Analgesics & Antipyretics",
        "sku": "SKU-ACEC-PARA",
        "barcode": "615100000010",
        "prescription": True,
        "cost": Decimal("1400.00"),
        "price": Decimal("2200.00"),
        "qty": 85,
        "days_to_expiry": 500,
    },

    # 2. Antibiotics & Antifungals
    {
        "name": "Amoxicillin 500mg Capsules (Pack of 100)",
        "generic_name": "Amoxicillin",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-AMOX-500",
        "barcode": "615100000011",
        "prescription": True,
        "cost": Decimal("1800.00"),
        "price": Decimal("2800.00"),
        "qty": 160,
        "days_to_expiry": 480,
    },
    {
        "name": "Augmentin 625mg Tablets (Pack of 14)",
        "generic_name": "Amoxicillin / Clavulanic Acid",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-AUG-625",
        "barcode": "615100000012",
        "prescription": True,
        "cost": Decimal("4500.00"),
        "price": Decimal("6800.00"),
        "qty": 95,
        "days_to_expiry": 420,
    },
    {
        "name": "Augmentin 1g Tablets (Pack of 14)",
        "generic_name": "Amoxicillin / Clavulanic Acid",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-AUG-1G",
        "barcode": "615100000013",
        "prescription": True,
        "cost": Decimal("6200.00"),
        "price": Decimal("9200.00"),
        "qty": 70,
        "days_to_expiry": 390,
    },
    {
        "name": "Ciprofloxacin 500mg Tablets (Pack of 10)",
        "generic_name": "Ciprofloxacin Hydrochloride",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-CIPRO-500",
        "barcode": "615100000014",
        "prescription": True,
        "cost": Decimal("750.00"),
        "price": Decimal("1300.00"),
        "qty": 240,
        "days_to_expiry": 600,
    },
    {
        "name": "Azithromycin 500mg Tablets (Zithromax Generic 3s)",
        "generic_name": "Azithromycin Dihydrate",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-AZITH-500",
        "barcode": "615100000015",
        "prescription": True,
        "cost": Decimal("1100.00"),
        "price": Decimal("1900.00"),
        "qty": 150,
        "days_to_expiry": 520,
    },
    {
        "name": "Cefuroxime Axetil 500mg (Zinnat Generic 10s)",
        "generic_name": "Cefuroxime Axetil",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-CEFUR-500",
        "barcode": "615100000016",
        "prescription": True,
        "cost": Decimal("3800.00"),
        "price": Decimal("5800.00"),
        "qty": 80,
        "days_to_expiry": 450,
    },
    {
        "name": "Metronidazole 400mg Tablets (Flagyl Generic 100s)",
        "generic_name": "Metronidazole",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-METRO-400",
        "barcode": "615100000017",
        "prescription": True,
        "cost": Decimal("900.00"),
        "price": Decimal("1500.00"),
        "qty": 190,
        "days_to_expiry": 750,
    },
    {
        "name": "Fluconazole 150mg Single Capsule (Diflucan Generic)",
        "generic_name": "Fluconazole",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-FLUC-150",
        "barcode": "615100000018",
        "prescription": False,
        "cost": Decimal("400.00"),
        "price": Decimal("850.00"),
        "qty": 210,
        "days_to_expiry": 900,
    },
    {
        "name": "Erythromycin 500mg Tablets (Pack of 100)",
        "generic_name": "Erythromycin Stearate",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-ERYTH-500",
        "barcode": "615100000019",
        "prescription": True,
        "cost": Decimal("2100.00"),
        "price": Decimal("3200.00"),
        "qty": 65,
        "days_to_expiry": 360,
    },
    {
        "name": "Doxycycline 100mg Capsules (Pack of 100)",
        "generic_name": "Doxycycline Hyclate",
        "category": "Antibiotics & Antifungals",
        "sku": "SKU-DOXY-100",
        "barcode": "615100000020",
        "prescription": True,
        "cost": Decimal("1300.00"),
        "price": Decimal("2200.00"),
        "qty": 110,
        "days_to_expiry": 580,
    },

    # 3. Antimalarials & Antiparasitics
    {
        "name": "Coartem 80/480mg Tablets (Pack of 6)",
        "generic_name": "Artemether / Lumefantrine",
        "category": "Antimalarials",
        "sku": "SKU-COART-80",
        "barcode": "615100000021",
        "prescription": False,
        "cost": Decimal("2800.00"),
        "price": Decimal("4200.00"),
        "qty": 175,
        "days_to_expiry": 480,
    },
    {
        "name": "Lonart DS Tablets (Pack of 6)",
        "generic_name": "Artemether / Lumefantrine",
        "category": "Antimalarials",
        "sku": "SKU-LONART-DS",
        "barcode": "615100000022",
        "prescription": False,
        "cost": Decimal("2100.00"),
        "price": Decimal("3200.00"),
        "qty": 220,
        "days_to_expiry": 540,
    },
    {
        "name": "Amatem Softgel Capsules (Pack of 6)",
        "generic_name": "Artemether / Lumefantrine",
        "category": "Antimalarials",
        "sku": "SKU-AMATEM-SG",
        "barcode": "615100000023",
        "prescription": False,
        "cost": Decimal("2300.00"),
        "price": Decimal("3500.00"),
        "qty": 140,
        "days_to_expiry": 510,
    },
    {
        "name": "P-Alaxin Tablets (Artenimol / Piperaquine)",
        "generic_name": "Dihydroartemisinin / Piperaquine",
        "category": "Antimalarials",
        "sku": "SKU-PALAXIN-TAB",
        "barcode": "615100000024",
        "prescription": False,
        "cost": Decimal("2600.00"),
        "price": Decimal("3900.00"),
        "qty": 115,
        "days_to_expiry": 620,
    },
    {
        "name": "Fansidar Tablets (SP for Pregnancy 3s)",
        "generic_name": "Sulfadoxine / Pyrimethamine",
        "category": "Antimalarials",
        "sku": "SKU-FANSIDAR-3",
        "barcode": "615100000025",
        "prescription": False,
        "cost": Decimal("600.00"),
        "price": Decimal("1100.00"),
        "qty": 160,
        "days_to_expiry": 750,
    },
    {
        "name": "Albendazole 400mg Chewable Tablet (Zentel Generic)",
        "generic_name": "Albendazole",
        "category": "Antimalarials",
        "sku": "SKU-ALBEN-400",
        "barcode": "615100000026",
        "prescription": False,
        "cost": Decimal("250.00"),
        "price": Decimal("500.00"),
        "qty": 280,
        "days_to_expiry": 820,
    },
    {
        "name": "Mebendazole 100mg Tablets (Vermox Generic 6s)",
        "generic_name": "Mebendazole",
        "category": "Antimalarials",
        "sku": "SKU-MEBEN-100",
        "barcode": "615100000027",
        "prescription": False,
        "cost": Decimal("350.00"),
        "price": Decimal("700.00"),
        "qty": 190,
        "days_to_expiry": 680,
    },
    {
        "name": "Artesunate Injection 60mg Vial",
        "generic_name": "Artesunate",
        "category": "Antimalarials",
        "sku": "SKU-ARTES-INJ",
        "barcode": "615100000028",
        "prescription": True,
        "cost": Decimal("1800.00"),
        "price": Decimal("2900.00"),
        "qty": 60,
        "days_to_expiry": 330,
    },

    # 4. Cardiovascular & Antihypertensives
    {
        "name": "Amlodipine 5mg Tablets (Pack of 30)",
        "generic_name": "Amlodipine Besylate",
        "category": "Cardiovascular",
        "sku": "SKU-AMLOD-5",
        "barcode": "615100000029",
        "prescription": True,
        "cost": Decimal("850.00"),
        "price": Decimal("1450.00"),
        "qty": 150,
        "days_to_expiry": 720,
    },
    {
        "name": "Amlodipine 10mg Tablets (Pack of 30)",
        "generic_name": "Amlodipine Besylate",
        "category": "Cardiovascular",
        "sku": "SKU-AMLOD-10",
        "barcode": "615100000030",
        "prescription": True,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 130,
        "days_to_expiry": 690,
    },
    {
        "name": "Lisinopril 10mg Tablets (Zestril Generic 30s)",
        "generic_name": "Lisinopril",
        "category": "Cardiovascular",
        "sku": "SKU-LISIN-10",
        "barcode": "615100000031",
        "prescription": True,
        "cost": Decimal("1100.00"),
        "price": Decimal("1850.00"),
        "qty": 100,
        "days_to_expiry": 640,
    },
    {
        "name": "Losartan Potassium 50mg (Cozaar Generic 30s)",
        "generic_name": "Losartan Potassium",
        "category": "Cardiovascular",
        "sku": "SKU-LOSAR-50",
        "barcode": "615100000032",
        "prescription": True,
        "cost": Decimal("1400.00"),
        "price": Decimal("2300.00"),
        "qty": 120,
        "days_to_expiry": 580,
    },
    {
        "name": "Losartan 50mg + HCTZ 12.5mg (Hyzaar Generic)",
        "generic_name": "Losartan / Hydrochlorothiazide",
        "category": "Cardiovascular",
        "sku": "SKU-LOSAR-HCTZ",
        "barcode": "615100000033",
        "prescription": True,
        "cost": Decimal("2200.00"),
        "price": Decimal("3500.00"),
        "qty": 90,
        "days_to_expiry": 520,
    },
    {
        "name": "Atorvastatin 20mg Tablets (Lipitor Generic 30s)",
        "generic_name": "Atorvastatin Calcium",
        "category": "Cardiovascular",
        "sku": "SKU-ATOR-20",
        "barcode": "615100000034",
        "prescription": True,
        "cost": Decimal("1800.00"),
        "price": Decimal("3000.00"),
        "qty": 140,
        "days_to_expiry": 610,
    },
    {
        "name": "Rosuvastatin 10mg Tablets (Crestor Generic 30s)",
        "generic_name": "Rosuvastatin Calcium",
        "category": "Cardiovascular",
        "sku": "SKU-ROSUV-10",
        "barcode": "615100000035",
        "prescription": True,
        "cost": Decimal("2900.00"),
        "price": Decimal("4600.00"),
        "qty": 85,
        "days_to_expiry": 550,
    },
    {
        "name": "Hydrochlorothiazide 25mg Tablets (Pack of 100)",
        "generic_name": "Hydrochlorothiazide",
        "category": "Cardiovascular",
        "sku": "SKU-HCTZ-25",
        "barcode": "615100000036",
        "prescription": True,
        "cost": Decimal("750.00"),
        "price": Decimal("1300.00"),
        "qty": 110,
        "days_to_expiry": 780,
    },
    {
        "name": "Bisoprolol 5mg Tablets (Concor Generic 30s)",
        "generic_name": "Bisoprolol Fumarate",
        "category": "Cardiovascular",
        "sku": "SKU-BISO-5",
        "barcode": "615100000037",
        "prescription": True,
        "cost": Decimal("2400.00"),
        "price": Decimal("3800.00"),
        "qty": 70,
        "days_to_expiry": 460,
    },
    {
        "name": "Telmisartan 40mg Tablets (Micardis Generic 30s)",
        "generic_name": "Telmisartan",
        "category": "Cardiovascular",
        "sku": "SKU-TELMI-40",
        "barcode": "615100000038",
        "prescription": True,
        "cost": Decimal("2100.00"),
        "price": Decimal("3400.00"),
        "qty": 65,
        "days_to_expiry": 590,
    },

    # 5. Diabetes & Endocrine Care
    {
        "name": "Metformin 500mg Tablets (Glucophage Generic 100s)",
        "generic_name": "Metformin Hydrochloride",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-MET-500",
        "barcode": "615100000039",
        "prescription": True,
        "cost": Decimal("1200.00"),
        "price": Decimal("1950.00"),
        "qty": 200,
        "days_to_expiry": 800,
    },
    {
        "name": "Metformin 1000mg Extended Release (XR 30s)",
        "generic_name": "Metformin Hydrochloride XR",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-MET-1000-XR",
        "barcode": "615100000040",
        "prescription": True,
        "cost": Decimal("2200.00"),
        "price": Decimal("3500.00"),
        "qty": 110,
        "days_to_expiry": 650,
    },
    {
        "name": "Glimepiride 2mg Tablets (Amaryl Generic 30s)",
        "generic_name": "Glimepiride",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-GLIM-2",
        "barcode": "615100000041",
        "prescription": True,
        "cost": Decimal("900.00"),
        "price": Decimal("1550.00"),
        "qty": 130,
        "days_to_expiry": 520,
    },
    {
        "name": "Glibenclamide 5mg Tablets (Daonil Generic 100s)",
        "generic_name": "Glibenclamide",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-GLIB-5",
        "barcode": "615100000042",
        "prescription": True,
        "cost": Decimal("800.00"),
        "price": Decimal("1400.00"),
        "qty": 90,
        "days_to_expiry": 740,
    },
    {
        "name": "Vildagliptin 50mg Tablets (Galvus Generic 30s)",
        "generic_name": "Vildagliptin",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-VILDA-50",
        "barcode": "615100000043",
        "prescription": True,
        "cost": Decimal("5500.00"),
        "price": Decimal("8200.00"),
        "qty": 45,
        "days_to_expiry": 430,
    },
    {
        "name": "Accu-Chek Active Test Strips (Pack of 50)",
        "generic_name": "Blood Glucose Test Strips",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-ACCU-STRIPS",
        "barcode": "615100000044",
        "prescription": False,
        "cost": Decimal("8500.00"),
        "price": Decimal("11500.00"),
        "qty": 60,
        "days_to_expiry": 300,
    },
    {
        "name": "Mixtard 30/70 Insulin 100IU/ml (10ml Vial)",
        "generic_name": "Human Insulin Biphasic",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-MIXTARD-10",
        "barcode": "615100000045",
        "prescription": True,
        "cost": Decimal("4800.00"),
        "price": Decimal("7200.00"),
        "qty": 40,
        "days_to_expiry": 240,
    },
    {
        "name": "Levothyroxine 100mcg Tablets (Eltroxin 100s)",
        "generic_name": "Levothyroxine Sodium",
        "category": "Diabetes & Endocrine",
        "sku": "SKU-LEVO-100",
        "barcode": "615100000046",
        "prescription": True,
        "cost": Decimal("3200.00"),
        "price": Decimal("4900.00"),
        "qty": 55,
        "days_to_expiry": 580,
    },

    # 6. Gastrointestinal & Antacids
    {
        "name": "Omeprazole 20mg Capsules (Losec Generic 30s)",
        "generic_name": "Omeprazole",
        "category": "Gastrointestinal",
        "sku": "SKU-OMEP-20",
        "barcode": "615100000047",
        "prescription": False,
        "cost": Decimal("600.00"),
        "price": Decimal("1100.00"),
        "qty": 260,
        "days_to_expiry": 620,
    },
    {
        "name": "Esomeprazole 40mg Tablets (Nexium Generic 28s)",
        "generic_name": "Esomeprazole Magnesium",
        "category": "Gastrointestinal",
        "sku": "SKU-ESOM-40",
        "barcode": "615100000048",
        "prescription": True,
        "cost": Decimal("3200.00"),
        "price": Decimal("4900.00"),
        "qty": 85,
        "days_to_expiry": 490,
    },
    {
        "name": "Gaviscon Double Action Liquid (200ml Bottle)",
        "generic_name": "Sodium Alginate / Calcium Carbonate",
        "category": "Gastrointestinal",
        "sku": "SKU-GAVIS-200",
        "barcode": "615100000049",
        "prescription": False,
        "cost": Decimal("2400.00"),
        "price": Decimal("3600.00"),
        "qty": 95,
        "days_to_expiry": 450,
    },
    {
        "name": "Gestid Antacid Suspension (200ml Bottle)",
        "generic_name": "Magnesium Trisilicate / Aluminium Hydroxide",
        "category": "Gastrointestinal",
        "sku": "SKU-GESTID-200",
        "barcode": "615100000050",
        "prescription": False,
        "cost": Decimal("900.00"),
        "price": Decimal("1500.00"),
        "qty": 140,
        "days_to_expiry": 540,
    },
    {
        "name": "Loperamide 2mg Capsules (Imodium Generic 10s)",
        "generic_name": "Loperamide Hydrochloride",
        "category": "Gastrointestinal",
        "sku": "SKU-LOPER-2",
        "barcode": "615100000051",
        "prescription": False,
        "cost": Decimal("350.00"),
        "price": Decimal("700.00"),
        "qty": 180,
        "days_to_expiry": 720,
    },
    {
        "name": "Oral Rehydration Salts (ORS Sachet Pack of 10)",
        "generic_name": "WHO Formula ORS",
        "category": "Gastrointestinal",
        "sku": "SKU-ORS-10",
        "barcode": "615100000052",
        "prescription": False,
        "cost": Decimal("800.00"),
        "price": Decimal("1400.00"),
        "qty": 220,
        "days_to_expiry": 850,
    },
    {
        "name": "Bisacodyl 5mg Tablets (Dulcolax Generic 30s)",
        "generic_name": "Bisacodyl",
        "category": "Gastrointestinal",
        "sku": "SKU-BISA-5",
        "barcode": "615100000053",
        "prescription": False,
        "cost": Decimal("650.00"),
        "price": Decimal("1200.00"),
        "qty": 130,
        "days_to_expiry": 600,
    },
    {
        "name": "Metoclopramide 10mg (Maxolon Generic 100s)",
        "generic_name": "Metoclopramide Hydrochloride",
        "category": "Gastrointestinal",
        "sku": "SKU-METOC-10",
        "barcode": "615100000054",
        "prescription": True,
        "cost": Decimal("800.00"),
        "price": Decimal("1350.00"),
        "qty": 90,
        "days_to_expiry": 690,
    },
    {
        "name": "Hyoscine Butylbromide 10mg (Buscopan Generic 20s)",
        "generic_name": "Hyoscine Butylbromide",
        "category": "Gastrointestinal",
        "sku": "SKU-BUSCO-10",
        "barcode": "615100000055",
        "prescription": False,
        "cost": Decimal("1100.00"),
        "price": Decimal("1800.00"),
        "qty": 115,
        "days_to_expiry": 580,
    },

    # 7. Respiratory, Cough & Allergy
    {
        "name": "Cetirizine 10mg Tablets (Zyrtec Generic 30s)",
        "generic_name": "Cetirizine Hydrochloride",
        "category": "Respiratory & Allergy",
        "sku": "SKU-CETIR-10",
        "barcode": "615100000056",
        "prescription": False,
        "cost": Decimal("500.00"),
        "price": Decimal("950.00"),
        "qty": 250,
        "days_to_expiry": 700,
    },
    {
        "name": "Loratadine 10mg Tablets (Claritin Generic 30s)",
        "generic_name": "Loratadine",
        "category": "Respiratory & Allergy",
        "sku": "SKU-LORAT-10",
        "barcode": "615100000057",
        "prescription": False,
        "cost": Decimal("650.00"),
        "price": Decimal("1200.00"),
        "qty": 170,
        "days_to_expiry": 650,
    },
    {
        "name": "Chlorpheniramine 4mg (Piriton Generic 1000s)",
        "generic_name": "Chlorpheniramine Maleate",
        "category": "Respiratory & Allergy",
        "sku": "SKU-PIRIT-4",
        "barcode": "615100000058",
        "prescription": False,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 80,
        "days_to_expiry": 900,
    },
    {
        "name": "Ventolin Inhaler 100mcg (Salbutamol Evohaler)",
        "generic_name": "Salbutamol Sulfate",
        "category": "Respiratory & Allergy",
        "sku": "SKU-VENT-INH",
        "barcode": "615100000059",
        "prescription": True,
        "cost": Decimal("3400.00"),
        "price": Decimal("5200.00"),
        "qty": 90,
        "days_to_expiry": 450,
    },
    {
        "name": "Seretide Evohaler 25/125mcg (Fluticasone/Salmeterol)",
        "generic_name": "Salmeterol / Fluticasone Propionate",
        "category": "Respiratory & Allergy",
        "sku": "SKU-SERET-125",
        "barcode": "615100000060",
        "prescription": True,
        "cost": Decimal("11500.00"),
        "price": Decimal("16000.00"),
        "qty": 25,
        "days_to_expiry": 380,
    },
    {
        "name": "Benylin 4Flu Liquid (100ml Bottle)",
        "generic_name": "Diphenhydramine / Pseudoephedrine",
        "category": "Respiratory & Allergy",
        "sku": "SKU-BENY-4FLU",
        "barcode": "615100000061",
        "prescription": False,
        "cost": Decimal("1600.00"),
        "price": Decimal("2500.00"),
        "qty": 110,
        "days_to_expiry": 480,
    },
    {
        "name": "Tutu Cough Syrup Expectorant (100ml)",
        "generic_name": "Guaifenesin / Ammonium Chloride",
        "category": "Respiratory & Allergy",
        "sku": "SKU-TUTU-SYR",
        "barcode": "615100000062",
        "prescription": False,
        "cost": Decimal("850.00"),
        "price": Decimal("1400.00"),
        "qty": 130,
        "days_to_expiry": 520,
    },
    {
        "name": "Procold Caplets (Flu & Sinus Relief 10s)",
        "generic_name": "Paracetamol / Pseudoephedrine / Chlorpheniramine",
        "category": "Respiratory & Allergy",
        "sku": "SKU-PROCOLD-10",
        "barcode": "615100000063",
        "prescription": False,
        "cost": Decimal("500.00"),
        "price": Decimal("900.00"),
        "qty": 210,
        "days_to_expiry": 600,
    },
    {
        "name": "Strepsils Honey & Lemon Lozenges (Pack of 24)",
        "generic_name": "Dichlorobenzyl Alcohol / Amylmetacresol",
        "category": "Respiratory & Allergy",
        "sku": "SKU-STREP-HON",
        "barcode": "615100000064",
        "prescription": False,
        "cost": Decimal("1400.00"),
        "price": Decimal("2200.00"),
        "qty": 140,
        "days_to_expiry": 700,
    },
    {
        "name": "Otrivin Adult Nasal Spray 0.1% (10ml)",
        "generic_name": "Xylometazoline Hydrochloride",
        "category": "Respiratory & Allergy",
        "sku": "SKU-OTRIV-10ML",
        "barcode": "615100000065",
        "prescription": False,
        "cost": Decimal("2200.00"),
        "price": Decimal("3400.00"),
        "qty": 75,
        "days_to_expiry": 420,
    },

    # 8. Vitamins, Minerals & Nutritional Supplements
    {
        "name": "Vitamin C 1000mg Effervescent (Redoxon Generic 20s)",
        "generic_name": "Ascorbic Acid / Zinc",
        "category": "Vitamins & Supplements",
        "sku": "SKU-VITC-1000",
        "barcode": "615100000066",
        "prescription": False,
        "cost": Decimal("1800.00"),
        "price": Decimal("2800.00"),
        "qty": 190,
        "days_to_expiry": 540,
    },
    {
        "name": "Vitamin C 100mg Chewable Orange (Pack of 100)",
        "generic_name": "Ascorbic Acid",
        "category": "Vitamins & Supplements",
        "sku": "SKU-VITC-CHEW",
        "barcode": "615100000067",
        "prescription": False,
        "cost": Decimal("600.00"),
        "price": Decimal("1100.00"),
        "qty": 300,
        "days_to_expiry": 800,
    },
    {
        "name": "Wellwoman Original Capsules (Pack of 30)",
        "generic_name": "Multivitamin & Micronutrients for Women",
        "category": "Vitamins & Supplements",
        "sku": "SKU-WELL-WOMAN",
        "barcode": "615100000068",
        "prescription": False,
        "cost": Decimal("4800.00"),
        "price": Decimal("7200.00"),
        "qty": 65,
        "days_to_expiry": 600,
    },
    {
        "name": "Wellman Original Tablets (Pack of 30)",
        "generic_name": "Multivitamin & Micronutrients for Men",
        "category": "Vitamins & Supplements",
        "sku": "SKU-WELL-MAN",
        "barcode": "615100000069",
        "prescription": False,
        "cost": Decimal("4800.00"),
        "price": Decimal("7200.00"),
        "qty": 70,
        "days_to_expiry": 600,
    },
    {
        "name": "Pregnacare Plus Dual Pack (56 Tablets/Capsules)",
        "generic_name": "Prenatal Micronutrients & DHA",
        "category": "Vitamins & Supplements",
        "sku": "SKU-PREG-PLUS",
        "barcode": "615100000070",
        "prescription": False,
        "cost": Decimal("8500.00"),
        "price": Decimal("12500.00"),
        "qty": 50,
        "days_to_expiry": 500,
    },
    {
        "name": "Feroglobin-B12 Blood Building Liquid (200ml)",
        "generic_name": "Iron / Zinc / B-Complex Liquid",
        "category": "Vitamins & Supplements",
        "sku": "SKU-FEROG-200",
        "barcode": "615100000071",
        "prescription": False,
        "cost": Decimal("3200.00"),
        "price": Decimal("4800.00"),
        "qty": 85,
        "days_to_expiry": 420,
    },
    {
        "name": "Vitamin E 400IU Softgels (Evion Generic 30s)",
        "generic_name": "d-alpha Tocopherol",
        "category": "Vitamins & Supplements",
        "sku": "SKU-VITE-400",
        "barcode": "615100000072",
        "prescription": False,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 140,
        "days_to_expiry": 750,
    },
    {
        "name": "Calcium + Vitamin D3 Tablets (Osteocare Generic 30s)",
        "generic_name": "Calcium Carbonate / Vitamin D3",
        "category": "Vitamins & Supplements",
        "sku": "SKU-CALC-D3",
        "barcode": "615100000073",
        "prescription": False,
        "cost": Decimal("2400.00"),
        "price": Decimal("3800.00"),
        "qty": 90,
        "days_to_expiry": 680,
    },
    {
        "name": "Folic Acid 5mg Tablets (Pack of 100)",
        "generic_name": "Folic Acid",
        "category": "Vitamins & Supplements",
        "sku": "SKU-FOLIC-5",
        "barcode": "615100000074",
        "prescription": False,
        "cost": Decimal("400.00"),
        "price": Decimal("750.00"),
        "qty": 240,
        "days_to_expiry": 850,
    },
    {
        "name": "Cod Liver Oil 1000mg Capsules (Seven Seas 100s)",
        "generic_name": "Cod Liver Oil / Omega-3",
        "category": "Vitamins & Supplements",
        "sku": "SKU-COD-1000",
        "barcode": "615100000075",
        "prescription": False,
        "cost": Decimal("3800.00"),
        "price": Decimal("5600.00"),
        "qty": 65,
        "days_to_expiry": 600,
    },

    # 9. Dermatological & Topical Care
    {
        "name": "Hydrocortisone 1% Cream (15g Tube)",
        "generic_name": "Hydrocortisone Acetate",
        "category": "Dermatological",
        "sku": "SKU-HYDRO-CRM",
        "barcode": "615100000076",
        "prescription": False,
        "cost": Decimal("450.00"),
        "price": Decimal("850.00"),
        "qty": 160,
        "days_to_expiry": 580,
    },
    {
        "name": "Clotrimazole 1% Cream (Canesten Generic 20g)",
        "generic_name": "Clotrimazole",
        "category": "Dermatological",
        "sku": "SKU-CLOTR-CRM",
        "barcode": "615100000077",
        "prescription": False,
        "cost": Decimal("550.00"),
        "price": Decimal("1000.00"),
        "qty": 180,
        "days_to_expiry": 650,
    },
    {
        "name": "Funbact-A Triple Action Cream (30g Tube)",
        "generic_name": "Clotrimazole / Betamethasone / Neomycin",
        "category": "Dermatological",
        "sku": "SKU-FUNBACT-30",
        "barcode": "615100000078",
        "prescription": False,
        "cost": Decimal("900.00"),
        "price": Decimal("1500.00"),
        "qty": 220,
        "days_to_expiry": 700,
    },
    {
        "name": "Skineal Antifungal & Antibacterial Cream (15g)",
        "generic_name": "Ketoconazole / Clobetasol / Neomycin",
        "category": "Dermatological",
        "sku": "SKU-SKINEAL-15",
        "barcode": "615100000079",
        "prescription": False,
        "cost": Decimal("850.00"),
        "price": Decimal("1450.00"),
        "qty": 190,
        "days_to_expiry": 640,
    },
    {
        "name": "Calamine Lotion BP (100ml Bottle)",
        "generic_name": "Calamine / Zinc Oxide",
        "category": "Dermatological",
        "sku": "SKU-CALAM-100",
        "barcode": "615100000080",
        "prescription": False,
        "cost": Decimal("600.00"),
        "price": Decimal("1100.00"),
        "qty": 110,
        "days_to_expiry": 720,
    },
    {
        "name": "Sudocrem Antiseptic Healing Cream (60g Jar)",
        "generic_name": "Zinc Oxide / Benzyl Benzoate",
        "category": "Dermatological",
        "sku": "SKU-SUDO-60G",
        "barcode": "615100000081",
        "prescription": False,
        "cost": Decimal("2800.00"),
        "price": Decimal("4200.00"),
        "qty": 75,
        "days_to_expiry": 800,
    },
    {
        "name": "Dettol Antiseptic Liquid (250ml Bottle)",
        "generic_name": "Chloroxylenol",
        "category": "Dermatological",
        "sku": "SKU-DETTOL-250",
        "barcode": "615100000082",
        "prescription": False,
        "cost": Decimal("1600.00"),
        "price": Decimal("2400.00"),
        "qty": 140,
        "days_to_expiry": 900,
    },
    {
        "name": "Methylated Spirit 70% (200ml Bottle)",
        "generic_name": "Denatured Ethanol",
        "category": "Dermatological",
        "sku": "SKU-SPIRIT-200",
        "barcode": "615100000083",
        "prescription": False,
        "cost": Decimal("450.00"),
        "price": Decimal("800.00"),
        "qty": 200,
        "days_to_expiry": 1000,
    },

    # 10. Ophthalmic & ENT Preparations (Eyes & Ears)
    {
        "name": "Chloramphenicol 0.5% Eye Drops (10ml Bottle)",
        "generic_name": "Chloramphenicol",
        "category": "Ophthalmic & ENT",
        "sku": "SKU-CHLOR-EYE",
        "barcode": "615100000084",
        "prescription": True,
        "cost": Decimal("450.00"),
        "price": Decimal("850.00"),
        "qty": 130,
        "days_to_expiry": 365,
    },
    {
        "name": "Gentamicin 0.3% Eye/Ear Drops (10ml Bottle)",
        "generic_name": "Gentamicin Sulfate",
        "category": "Ophthalmic & ENT",
        "sku": "SKU-GENT-EYE",
        "barcode": "615100000085",
        "prescription": True,
        "cost": Decimal("500.00"),
        "price": Decimal("900.00"),
        "qty": 110,
        "days_to_expiry": 400,
    },
    {
        "name": "Tears Naturale Lubricant Eye Drops (15ml)",
        "generic_name": "Dextran 70 / Hydroxypropyl Methylcellulose",
        "category": "Ophthalmic & ENT",
        "sku": "SKU-TEARS-NAT",
        "barcode": "615100000086",
        "prescription": False,
        "cost": Decimal("2400.00"),
        "price": Decimal("3800.00"),
        "qty": 60,
        "days_to_expiry": 550,
    },
    {
        "name": "Ciprobiotic Ear Drops 0.3% (10ml)",
        "generic_name": "Ciprofloxacin / Dexamethasone",
        "category": "Ophthalmic & ENT",
        "sku": "SKU-CIPRO-EAR",
        "barcode": "615100000087",
        "prescription": True,
        "cost": Decimal("1800.00"),
        "price": Decimal("2900.00"),
        "qty": 70,
        "days_to_expiry": 420,
    },
    {
        "name": "Cerumol Ear Wax Drops (11ml Bottle)",
        "generic_name": "Arachis Oil / Chlorobutanol",
        "category": "Ophthalmic & ENT",
        "sku": "SKU-CERUMOL-11",
        "barcode": "615100000088",
        "prescription": False,
        "cost": Decimal("3100.00"),
        "price": Decimal("4800.00"),
        "qty": 40,
        "days_to_expiry": 600,
    },

    # 11. Central Nervous System & Psychiatric
    {
        "name": "Diazepam 5mg Tablets (Valium Generic 100s)",
        "generic_name": "Diazepam",
        "category": "Central Nervous System",
        "sku": "SKU-DIAZ-5",
        "barcode": "615100000089",
        "prescription": True,
        "cost": Decimal("1500.00"),
        "price": Decimal("2500.00"),
        "qty": 40,
        "days_to_expiry": 700,
    },
    {
        "name": "Amitriptyline 25mg Tablets (Pack of 100)",
        "generic_name": "Amitriptyline Hydrochloride",
        "category": "Central Nervous System",
        "sku": "SKU-AMIT-25",
        "barcode": "615100000090",
        "prescription": True,
        "cost": Decimal("1200.00"),
        "price": Decimal("2100.00"),
        "qty": 55,
        "days_to_expiry": 650,
    },
    {
        "name": "Pregabalin 75mg Capsules (Lyrica Generic 14s)",
        "generic_name": "Pregabalin",
        "category": "Central Nervous System",
        "sku": "SKU-PREG-75",
        "barcode": "615100000091",
        "prescription": True,
        "cost": Decimal("3200.00"),
        "price": Decimal("5000.00"),
        "qty": 45,
        "days_to_expiry": 520,
    },
    {
        "name": "Carbamazepine 200mg (Tegretol Generic 100s)",
        "generic_name": "Carbamazepine",
        "category": "Central Nervous System",
        "sku": "SKU-CARB-200",
        "barcode": "615100000092",
        "prescription": True,
        "cost": Decimal("2200.00"),
        "price": Decimal("3600.00"),
        "qty": 50,
        "days_to_expiry": 600,
    },

    # 12. First Aid, Medical Supplies & Hygiene
    {
        "name": "Sterile Gauze Bandage 3 Inch (Pack of 12)",
        "generic_name": "Cotton Gauze Bandage",
        "category": "Medical Supplies",
        "sku": "SKU-BAND-3IN",
        "barcode": "615100000093",
        "prescription": False,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 120,
        "days_to_expiry": 1200,
    },
    {
        "name": "Adhesive Plaster Strips (Hansaplast Pack of 100)",
        "generic_name": "First Aid Adhesive Bandages",
        "category": "Medical Supplies",
        "sku": "SKU-PLAST-100",
        "barcode": "615100000094",
        "prescription": False,
        "cost": Decimal("1500.00"),
        "price": Decimal("2400.00"),
        "qty": 150,
        "days_to_expiry": 1400,
    },
    {
        "name": "Cotton Wool Roll 500g (Hospital Grade)",
        "generic_name": "Absorbent Cotton Wool",
        "category": "Medical Supplies",
        "sku": "SKU-COTTON-500",
        "barcode": "615100000095",
        "prescription": False,
        "cost": Decimal("1800.00"),
        "price": Decimal("2800.00"),
        "qty": 90,
        "days_to_expiry": 1500,
    },
    {
        "name": "Disposable Surgical Gloves (Box of 100, Medium)",
        "generic_name": "Latex Examination Gloves",
        "category": "Medical Supplies",
        "sku": "SKU-GLOVES-M",
        "barcode": "615100000096",
        "prescription": False,
        "cost": Decimal("4200.00"),
        "price": Decimal("6500.00"),
        "qty": 65,
        "days_to_expiry": 1000,
    },
    {
        "name": "Digital Clinical Thermometer (Oral/Axillary)",
        "generic_name": "Electronic Digital Thermometer",
        "category": "Medical Supplies",
        "sku": "SKU-THERM-DIG",
        "barcode": "615100000097",
        "prescription": False,
        "cost": Decimal("1500.00"),
        "price": Decimal("2500.00"),
        "qty": 80,
        "days_to_expiry": 1800,
    },
    {
        "name": "N95 Particulate Respirator Face Masks (Box of 20)",
        "generic_name": "N95 Protective Face Mask",
        "category": "Medical Supplies",
        "sku": "SKU-MASK-N95",
        "barcode": "615100000098",
        "prescription": False,
        "cost": Decimal("5500.00"),
        "price": Decimal("8500.00"),
        "qty": 45,
        "days_to_expiry": 1100,
    },
    {
        "name": "Blood Pressure Monitor Upper Arm (Omron Generic)",
        "generic_name": "Digital BP Monitor",
        "category": "Medical Supplies",
        "sku": "SKU-BP-MONITOR",
        "barcode": "615100000099",
        "prescription": False,
        "cost": Decimal("22000.00"),
        "price": Decimal("32000.00"),
        "qty": 20,
        "days_to_expiry": 1800,
    },
    {
        "name": "Hand Sanitizer Gel 70% Alcohol (500ml Pump)",
        "generic_name": "Alcohol Hand Rub",
        "category": "Medical Supplies",
        "sku": "SKU-SANITZ-500",
        "barcode": "615100000100",
        "prescription": False,
        "cost": Decimal("1200.00"),
        "price": Decimal("2000.00"),
        "qty": 100,
        "days_to_expiry": 730,
    },
]


def seed_database():
    config = AppConfig()
    db_m = DatabaseManager(config)
    today = date.today()
    now_iso = datetime.now(timezone.utc).isoformat()

    print(f"Total items to seed: {len(ITEMS_DATA)}")

    with db_m.get_session() as session:
        org = session.query(Organization).first()
        branch = session.query(Branch).first()
        user = session.query(User).first()

        if not org or not branch or not user:
            print("Error: Missing Organization, Branch, or User record in database.")
            return

        org_id = org.id
        branch_id = branch.id
        user_id = user.id

        # 1. Ensure categories exist
        category_names = sorted(list({item["category"] for item in ITEMS_DATA}))
        cat_map = {}
        for cname in category_names:
            cat = session.query(Category).filter_by(organization_id=org_id, name=cname).first()
            if not cat:
                cat = Category(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    name=cname,
                    is_active=True,
                )
                session.add(cat)
                session.flush()
                print(f"Created category: {cname}")
            cat_map[cname] = cat.id

        # 2. Insert or update the 100 products, prices, batches, and inventory records
        created_count = 0
        updated_count = 0

        for idx, data in enumerate(ITEMS_DATA, start=1):
            cat_id = cat_map[data["category"]]
            sku = data["sku"]
            name = data["name"]
            barcode = data["barcode"]
            generic = data["generic_name"]
            prescription = data["prescription"]
            cost = data["cost"]
            price = data["price"]
            qty = data["qty"]
            expiry_date_val = (today + timedelta(days=data["days_to_expiry"])).isoformat()
            batch_num = f"BTH-{today.strftime('%Y%m')}-{idx:03d}"

            product = session.query(Product).filter_by(organization_id=org_id, sku=sku).first()
            if not product:
                product = Product(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    sku=sku,
                    barcode=barcode,
                    name=name,
                    generic_name=generic,
                    category_id=cat_id,
                    prescription_required=prescription,
                    is_active=True,
                )
                session.add(product)
                session.flush()
                created_count += 1
            else:
                product.barcode = barcode
                product.name = name
                product.generic_name = generic
                product.category_id = cat_id
                product.prescription_required = prescription
                product.is_active = True
                updated_count += 1

            # Ensure ProductBranch link
            pb = session.query(ProductBranch).filter_by(product_id=product.id, branch_id=branch_id).first()
            if not pb:
                pb = ProductBranch(
                    id=str(uuid.uuid4()),
                    product_id=product.id,
                    branch_id=branch_id,
                    is_active=True,
                )
                session.add(pb)
                session.flush()

            # Ensure Price
            curr_price = (
                session.query(Price)
                .filter_by(organization_id=org_id, product_id=product.id, branch_id=branch_id, is_current=True)
                .first()
            )
            if not curr_price:
                curr_price = Price(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    product_id=product.id,
                    branch_id=branch_id,
                    selling_price=price,
                    currency="NGN",
                    is_current=True,
                    version=1,
                    effective_from=now_iso,
                    created_by_id=user_id,
                )
                session.add(curr_price)
                session.flush()
            else:
                curr_price.selling_price = price

            # Ensure Batch
            batch = session.query(Batch).filter_by(product_id=product.id, batch_number=batch_num).first()
            if not batch:
                batch = Batch(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    product_id=product.id,
                    batch_number=batch_num,
                    expiry_date=expiry_date_val,
                    purchase_price=cost,
                    received_date=today.isoformat(),
                    status=BatchStatus.ACTIVE.value,
                    notes="Automated inventory master stock intake",
                )
                session.add(batch)
                session.flush()

            # Ensure BranchInventory
            inv = session.query(BranchInventory).filter_by(
                organization_id=org_id, branch_id=branch_id, batch_id=batch.id
            ).first()
            if not inv:
                inv = BranchInventory(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    branch_id=branch_id,
                    batch_id=batch.id,
                    quantity=qty,
                    reserved_quantity=0,
                    status=InventoryStatus.AVAILABLE.value,
                )
                session.add(inv)
                session.flush()

                # Record Inventory Movement
                mov = InventoryMovement(
                    id=str(uuid.uuid4()),
                    organization_id=org_id,
                    branch_id=branch_id,
                    batch_id=batch.id,
                    movement_type=MovementType.OPENING_BALANCE.value,
                    quantity_change=qty,
                    quantity_before=0,
                    quantity_after=qty,
                    reference_type="OPENING_BALANCE",
                    reference_id=inv.id,
                    user_id=user_id,
                    notes=f"Initial stock load for {name} ({batch_num})",
                    local_timestamp=now_iso,
                    is_offline=True,
                )
                session.add(mov)
                session.flush()
            else:
                inv.quantity = qty
                inv.status = InventoryStatus.AVAILABLE.value

        session.commit()
        print(f"[SUCCESS] Successfully loaded inventory! Products created: {created_count}, updated: {updated_count}, Total: 100")


if __name__ == "__main__":
    seed_database()
